### ISSUE TITLE
Preserve ICC metadata from input images

### ISSUE THREAD

**Issue by behreajj** [Quickmarble/censor#2]
Hi,

Thank you for making this tool! It's very handy and I look forward to its future development. I ran into an issue, though:

For palettes saved in images with an embedded color profile, the analysis seems fine but the output image looks off because plot.png does not share the same color profile as the input. [Edit: Or the analysis is off and the output plot profile should be sRGB. I don't know, it's been a long day.]
![rybPalAdobe](https://user-images.githubusercontent.com/12038348/129813901-e9b83ae3-783b-479a-80b7-e64b74e40502.png)
![plot](https://user-images.githubusercontent.com/12038348/129813910-7d64a376-1616-41e3-b577-335f3a51e6d0.png)

Just in case there's any issue with the display of the images above, the input png was built from this GPL file, then had a profile assigned to it:

```gpl
GIMP Palette
Name: RYB
Columns: 4
255 0 0 FF0000 1
255 106 0 FF6A00 2
255 162 0 FFA200 3
255 207 0 FFCF00 4
255 255 0 FFFF00 5
129 212 26 81D41A 6
0 169 51 00A933 7
21 132 102 158466 8
17 89 166 1159A6 9
60 42 146 3C2A92 10
105 12 133 690C85 11
170 0 85 AA0055 12
```

The yellow green, for example, is #81D41A, but looks like #9dd339.

Thank you.

**Comment by Quickmarble** [comment]
Hello! At the moment, the analyser doesn't read or write ICC metadata when handling images and relies only on RGB values provided by the `image` library.
Currently, the library seems to be unable to handle ICC profiles: https://github.com/image-rs/image/issues/1030
I guess using something like `img-parts` in addition to `image` just for reading/writing ICC metadata is the optimal way for now. I'll try that.

**Comment by Quickmarble** [comment]
By the way, if you also want ICC metadata to affect how RGB values are converted to XYZ and forth, open a separate issue - it'll require actual interpretation of the profile.

**Comment by Quickmarble** [comment]
The issue should be resolved now; imagemagick's `identify -verbose` shows that the ICC profile of the analysis is the same as the one of your example. Though it's preserved only for PNG and JPEG at the moment (restrictions of `img-parts`). Reopen the issue if you encounter additional problems with the feature.
